# ================================================================================
# **Notice**: source codes for TAppEncoder are all inside the Lib folder.
# ================================================================================

# ================================================================================
#cc_library(
#    name = "TAppEncCfg",
#    srcs = ["TAppEncCfg.cpp"],
#    hdrs = ["TAppEncCfg.h"],
#    deps = [
#        "//HTM162/Lib/TLibCommon:TLibCommon",
#    ],
#)
#
#cc_library(
#    name = "TAppEncTop",
#    srcs = ["TAppEncTop.cpp"],
#    hdrs = ["TAppEncTop.h"],
#    deps = [
#        ":TAppEncCfg",
#        "//HTM162/Lib/TLibCommon:TLibCommon",
#    ],
#)
#cc_library(
#    name = "TAppEncTopAndCfg",
#    srcs = ["TAppEncTop.cpp", "TAppEncCfg.cpp"],
#    hdrs = ["TAppEncTop.h", "TAppEncCfg.h"],
#    deps = [
#        "//HTM162/Lib/TLibCommon:TLibCommon",
#    ],
#)

#cc_binary(
#    name = "TAppEncoder",
#    srcs = ["encmain.cpp"],
#    deps = [
##    	  ":TAppEncTopAndCfg",
#        "//tensorflow/cc:cc_ops",
#        "//tensorflow/core:tensorflow",
#        "//HTM162/Lib/TLibCommon:TLibCommon",
#    ],
#)
# ================================================================================