#cc_library(
#    name = "strtk",
#    hdrs = ["strtk.hpp"],
#)

cc_binary(
    name = "TAppClassifier",
    srcs = ["main.cpp"],
    deps = [
#    	  ":strtk",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/core:tensorflow",
    ],
)