cc_library(
    name = "TLibResnet",
#    srcs = ["ContextModel.cpp", 
#    		],
    hdrs = [
            "strtk.hpp",
            "TResnet.h"
    		],
    deps = [
    ],
    visibility = [
                "//HTM162/App/TAppEncoder:__pkg__",
                ],
)